# Generated by Django 4.2.6 on 2023-10-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='LGCY', max_length=100)),
                ('question_text', models.CharField(max_length=300)),
                ('answer_text', models.CharField(max_length=300)),
            ],
        ),
    ]
