# Generated by Django 4.2.6 on 2023-10-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_rename_questions_flashcards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcards',
            new_name='Flashcard',
        ),
    ]
